# Generated by Django 5.0.4 on 2024-04-26 19:30

import datetime
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calificación',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estrellas', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Empleo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Trabajador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('apellido', models.CharField(max_length=30)),
                ('dirección', models.TextField(default='', max_length=100)),
                ('ci', models.IntegerField(max_length=11)),
                ('empresa', models.CharField(max_length=30)),
                ('teléfono1', models.CharField(max_length=15)),
                ('teléfono2', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('imagen', models.ImageField(upload_to='empleados/imagen')),
                ('domicilio', models.BooleanField(default=True)),
                ('descripción', models.TextField(default='', max_length=100)),
                ('fecha_alta', models.DateField(default=datetime.date.today)),
                ('lat', models.DecimalField(decimal_places=7, max_digits=10)),
                ('lon', models.DecimalField(decimal_places=7, max_digits=10)),
                ('token', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('calificación', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uno.calificación')),
                ('empleo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uno.empleo')),
            ],
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.TextField(max_length=400)),
                ('trabajador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uno.trabajador')),
            ],
        ),
    ]
