# Generated by Django 5.0.4 on 2024-08-09 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uno', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='nombre',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='descripción',
            field=models.TextField(default='', max_length=400),
        ),
    ]
